from manimlib import *


class Pi(Scene):
    def construct(self):
        # grid=NumberPlane()
        # self.add(grid)
        cir=Circle(radius=0.5,color=WHITE)
        pi=Tex("\\pi",color=WHITE)
        day=Text("3.14",color=WHITE,font="Arial").move_to(1.5*DOWN)
        numbers=Text("3.141592653589793232846264338327950288419716939937...",color=WHITE,font="Arial").rotate_about_origin(-PI/2).shift(1.1*RIGHT).scale(0.3)
        numbers.apply_complex_function(lambda p: np.exp(p))
        self.play(Write(pi),ShowCreation(cir),run_time=2),self.wait(0.2)
        self.play(cir.animate.scale(5),pi.animate.scale(5))
        self.play(Rotating(pi,angle=TAU,rate_func=smooth,run_time=2),FadeIn(day,shift=DOWN))
        self.play(Write(numbers)),self.wait(0.5)
        numbers.add_updater(lambda m, dt: m.rotate(0.2*DEGREES))
        fml1=Tex("\\frac{C}{2R}=\\pi").next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml1), run_time=1.5),self.wait(3)
        fml1.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml2=Tex("{e}^{i\\pi}+1=0").next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml2), run_time=1.5),self.wait(3)
        fml2.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml3=Tex("\\int\\limits_{-\\infty}^{\\infty}{e}^{{-x}^{2}}\\mathrm{d}x=\\sqrt{\\pi }").next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml3), run_time=1.5),self.wait(5)
        fml3.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml4=Tex("\\sum_{n=1}^{\\infty}\\frac{1}{{n}^{2}}=\\frac{{\\pi}^{2}}{6} ").next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml4), run_time=1.5),self.wait(6)
        fml4.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml5=Tex("\\int\\limits_{-\\infty}^{\\infty}\\frac{\\sin x}{x}\\mathrm{d}x=\\pi ").next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml5), run_time=1.5),self.wait(6)
        fml5.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml6=Tex("\\Gamma \\left ( \\frac{1}{2}  \\right ) = \\sqrt{\\pi }").next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml6), run_time=1.5),self.wait(6)
        fml6.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml7=Tex("\\pi =  \\cfrac{4}{1 + \\cfrac{1^2}{3 + \\cfrac{2^2}{5 + \\cfrac{3^2}{7 + \\cfrac{4^2}{9+\\ddots } } } } }").scale(0.6).next_to([3.25,0,0],RIGHT,aligned_edge=LEFT)
        self.play(Write(fml7), run_time=1.5),self.wait(6)
        fml7.add_updater(lambda m, dt: m.rotate(0.1*DEGREES, about_point=ORIGIN))
        fml1.clear_updaters()
        self.play(fml1.animate.become(Tex("\\frac{C}{2R}=\\pi").move_to(1.5*UP)))
        self.wait(PI*10)
        self.play(*[FadeOut(mob) for mob in self.mobjects],run_time=3,rate_func=double_smooth)
